In [1]:
!pip install sklearn

In [2]:
import numpy as np
from sklearn import datasets

# I created a special python file that's full of helpers for our notebooks. 
# If you are code inclined, feel free to look inside the file and see what I'm doing there
# for others, this Helper file will just make some functions easier to handle for beginners
import Helpers

# Specifically, we want the helper for this Iris project
helper = Helpers.Iris

# sklearn comes with the whole Iris Dataset, so let's make sure to load it
iris = datasets.load_iris()

features = iris.data
labels = iris.target


flower_names = ["SETOSA", "VERSICOLOR", "VIRGINICA"]
total_classes = len(flower_names)

print("Total feature records: ", len(features))
print("\nFirst five records:", features[:5])

Total feature records:  150

First five records: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [3]:
print("total labels:", len(labels))
print("\nAll label records: ", labels)

total labels: 150

All label records:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Notice that all the records are sorted by type of flower. For training, we would rather have our data shuffled around, so we will load some helpers functions to shuffle them around and then verify that the order is now random.

In [4]:

features, labels = helper.shuffle_records(features, labels)

print("Total feature records: ", len(features))
print("Total labels: ", len(labels))
print("\nAll label records: ", labels)

Total feature records:  150
Total labels:  150

All label records:  [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 2 2
 1 1 2 1 0 1 2 0 0 1 1 0 2 0 0 1 1 2 1 2 2 1 0 0 2 2 0 0 0 1 2 0 2 2 0 1 1
 2 1 2 0 2 1 2 1 1 1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0
 1 2]


In [5]:
one_hot_labels = helper.convert_to_one_hot(labels, total_classes)

print("the original first 5 labels:", labels[:5])
print("\nFirst 5 one hot labels:", one_hot_labels[:5])

the original first 5 labels: [1 0 2 1 1]

First 5 one hot labels: [[0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]]


In [6]:
one_hot_labels.shape

(150, 3)

# BUILDING THE NEURAL NET #

In [7]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [8]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation="softmax"))
model.compile(loss="categorical_crossentropy", optimizer='adam', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [9]:
batch_size = 128

def TrainingLoop(number_of_epochs, verbose):
    model.fit(features,
             one_hot_labels,
             batch_size=batch_size,
             epochs=number_of_epochs,
             verbose=verbose,
             validation_split=.1)

In [10]:
TrainingLoop(1, 1)

Instructions for updating:
Use tf.cast instead.
Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 2s 12ms/step - loss: 2.8467 - acc: 0.3556 - val_loss: 3.7240 - val_acc: 0.1333


In [11]:
TrainingLoop(500, 0)
TrainingLoop(1, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 0s 37us/step - loss: 0.2973 - acc: 0.9556 - val_loss: 0.3496 - val_acc: 0.9333


In [12]:
TrainingLoop(10, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/10
135/135 [==============================] - 0s 52us/step - loss: 0.2971 - acc: 0.9556 - val_loss: 0.3490 - val_acc: 0.9333
Epoch 2/10
135/135 [==============================] - 0s 37us/step - loss: 0.2965 - acc: 0.9556 - val_loss: 0.3482 - val_acc: 0.9333
Epoch 3/10
135/135 [==============================] - 0s 37us/step - loss: 0.2954 - acc: 0.9556 - val_loss: 0.3473 - val_acc: 0.9333
Epoch 4/10
135/135 [==============================] - 0s 37us/step - loss: 0.2941 - acc: 0.9556 - val_loss: 0.3467 - val_acc: 1.0000
Epoch 5/10
135/135 [==============================] - 0s 44us/step - loss: 0.2926 - acc: 0.9630 - val_loss: 0.3464 - val_acc: 1.0000
Epoch 6/10
135/135 [==============================] - 0s 37us/step - loss: 0.2916 - acc: 0.9778 - val_loss: 0.3469 - val_acc: 1.0000
Epoch 7/10
135/135 [==============================] - 0s 52us/step - loss: 0.2908 - acc: 0.9778 - val_loss: 0.3474 - val_acc: 1.0000
Epoch 8/10
135/135 [====

In [13]:
features[0:3]

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3]])

In [14]:
one_hot_labels[0:3]

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [15]:
test_data = np.array([ [5.7, 3.8, 1.7, 0.3] ] )
result = model.predict( test_data, batch_size=1, verbose=1)
result

1/1 [==============================] - 0s 15ms/step


array([[9.8573643e-01, 1.4195374e-02, 6.8137626e-05]], dtype=float32)

In [16]:
highest_index = np.argmax(result, axis=1)[0]
flower_names[highest_index]

'SETOSA'